repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.21.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.7.0
          - pyflakes==2.3.1
          - flake8-docstrings==1.6.0
          - pydocstyle==6.0.0
          - flake8-comprehensions==3.5.0
          - flake8-noqa==1.1.0
          - mccabe==0.6.1
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # Use the ref you want to point at
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
