repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle
          - pyflakes
          - flake8-docstrings
          - pydocstyle
          - flake8-comprehensions
          - flake8-noqa
          - mccabe
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=pyproject.toml
        files: ^.*/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [manual]
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.5.1
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      - id: python-typing-update
        stages: [manual]
        args:
          - --py38-plus
          - --force
          - --black
          - --keep-updates
