name: Python checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include: # define single matrix case that performs upload
          - os: ubuntu-latest
            python: 3.9
            upload: true
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: pre-commit/action@v2.0.3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install .
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarballd
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
